### ISSUE TITLE
fanny.bmp file

### ISSUE THREAD

**Issue by ghost** [loneicewolf/fanny.bmp#1]
Sources:
https://www.hybrid-analysis.com/sample/ef3135e462540adfba00234d75c4b21430f5a9037b61e7dc1014c8711ddc0047/5640de9d0e316dee1267dd49

[fanny_worm.zip](https://github.com/loneicewolf/fanny.bmp/files/5613839/fanny_worm.zip)
password: infected

[fanny_payload.zip](https://github.com/loneicewolf/fanny.bmp/files/5613857/fanny_payload.zip)
password: infected

Brief:
https://securelist.com/a-fanny-equation-i-am-your-father-stuxnet/68787/

**Comment by loneicewolf** [comment]
Hello,  although this git wasn't made for contributions, this is very much appreciated! And it pointed out a few vital parts. I thank you @quosego for your time and energy for providing material; Although it wasn't exactly what I thought of sharing (In the link, secure list)  There are link files, and I was one of those early who just, "took a copy of the unknown malware" For, like - research purposes. Now in 2020- I know how damaging this worm or malware really was (still are, I should add!)

Which I thought of providing. (The exact same as in the securelist.com URL's screenshots) (These ones I mean specifically)

![Fanny5(NotTheMalware-JustAScreenshot)](https://user-images.githubusercontent.com/68499986/100591036-7cf8f980-32f5-11eb-9573-c97714c97457.jpg)

Those files,
- __d__.lnk

- __e__.lnk

- __f__.lnk

- __g__.lnk

- __h__.lnk

- __i__.lnk

- __j__.lnk

- fanny.bmp

And as well as some other things, such as a virtual Machine (Encrypted with same password I will be providing) with pre-installed ghidra, object dumps (examples, to get people going - if they are new **but still know what they are doing**)

Anyway, I will end this comment by saying it again, thanks for contributing!
It's very welcome.

Good day, on both you & the other possible future-readers!

**Comment by loneicewolf** [comment]
Just for further reader's; I'm providing the fanny sample now, check the repo.

Contact me for anything else, if something's unclear, or if assistance is needed.

william-martens@protonmail.ch
